# CMake generated Testfile for 
# Source directory: /home/runner/work/ggml/ggml/tests
# Build directory: /home/runner/work/ggml/ggml/_codeql_build_dir/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test-backend-ops "/home/runner/work/ggml/ggml/_codeql_build_dir/bin/test-backend-ops")
set_tests_properties(test-backend-ops PROPERTIES  ENVIRONMENT "LLVM_PROFILE_FILE=test-backend-ops.profraw" _BACKTRACE_TRIPLES "/home/runner/work/ggml/ggml/tests/CMakeLists.txt;168;add_test;/home/runner/work/ggml/ggml/tests/CMakeLists.txt;0;")
add_test(test-opt "/home/runner/work/ggml/ggml/_codeql_build_dir/bin/test-opt")
set_tests_properties(test-opt PROPERTIES  ENVIRONMENT "LLVM_PROFILE_FILE=test-opt.profraw" _BACKTRACE_TRIPLES "/home/runner/work/ggml/ggml/tests/CMakeLists.txt;178;add_test;/home/runner/work/ggml/ggml/tests/CMakeLists.txt;0;")
add_test(test-quantize-fns "/home/runner/work/ggml/ggml/_codeql_build_dir/bin/test-quantize-fns")
set_tests_properties(test-quantize-fns PROPERTIES  ENVIRONMENT "LLVM_PROFILE_FILE=test-quantize-fns.profraw" _BACKTRACE_TRIPLES "/home/runner/work/ggml/ggml/tests/CMakeLists.txt;187;add_test;/home/runner/work/ggml/ggml/tests/CMakeLists.txt;0;")
add_test(test-quantize-perf "/home/runner/work/ggml/ggml/_codeql_build_dir/bin/test-quantize-perf")
set_tests_properties(test-quantize-perf PROPERTIES  ENVIRONMENT "LLVM_PROFILE_FILE=test-quantize-perf.profraw" _BACKTRACE_TRIPLES "/home/runner/work/ggml/ggml/tests/CMakeLists.txt;196;add_test;/home/runner/work/ggml/ggml/tests/CMakeLists.txt;0;")
add_test(test-pool "/home/runner/work/ggml/ggml/_codeql_build_dir/bin/test-pool")
set_tests_properties(test-pool PROPERTIES  ENVIRONMENT "LLVM_PROFILE_FILE=test-pool.profraw" _BACKTRACE_TRIPLES "/home/runner/work/ggml/ggml/tests/CMakeLists.txt;208;add_test;/home/runner/work/ggml/ggml/tests/CMakeLists.txt;0;")
add_test(test-arange "/home/runner/work/ggml/ggml/_codeql_build_dir/bin/test-arange")
set_tests_properties(test-arange PROPERTIES  ENVIRONMENT "LLVM_PROFILE_FILE=test-arange.profraw" _BACKTRACE_TRIPLES "/home/runner/work/ggml/ggml/tests/CMakeLists.txt;220;add_test;/home/runner/work/ggml/ggml/tests/CMakeLists.txt;0;")
add_test(test-timestep_embedding "/home/runner/work/ggml/ggml/_codeql_build_dir/bin/test-timestep_embedding")
set_tests_properties(test-timestep_embedding PROPERTIES  ENVIRONMENT "LLVM_PROFILE_FILE=test-timestep_embedding.profraw" _BACKTRACE_TRIPLES "/home/runner/work/ggml/ggml/tests/CMakeLists.txt;232;add_test;/home/runner/work/ggml/ggml/tests/CMakeLists.txt;0;")
add_test(test-pad-reflect-1d "/home/runner/work/ggml/ggml/_codeql_build_dir/bin/test-pad-reflect-1d")
set_tests_properties(test-pad-reflect-1d PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/ggml/ggml/tests/CMakeLists.txt;241;add_test;/home/runner/work/ggml/ggml/tests/CMakeLists.txt;0;")
add_test(test-roll "/home/runner/work/ggml/ggml/_codeql_build_dir/bin/test-roll")
set_tests_properties(test-roll PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/ggml/ggml/tests/CMakeLists.txt;249;add_test;/home/runner/work/ggml/ggml/tests/CMakeLists.txt;0;")
add_test(test-conv-transpose "/home/runner/work/ggml/ggml/_codeql_build_dir/bin/test-conv-transpose")
set_tests_properties(test-conv-transpose PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/ggml/ggml/tests/CMakeLists.txt;257;add_test;/home/runner/work/ggml/ggml/tests/CMakeLists.txt;0;")
add_test(test-conv-transpose-1d "/home/runner/work/ggml/ggml/_codeql_build_dir/bin/test-conv-transpose-1d")
set_tests_properties(test-conv-transpose-1d PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/ggml/ggml/tests/CMakeLists.txt;264;add_test;/home/runner/work/ggml/ggml/tests/CMakeLists.txt;0;")
add_test(test-dup "/home/runner/work/ggml/ggml/_codeql_build_dir/bin/test-dup")
set_tests_properties(test-dup PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/ggml/ggml/tests/CMakeLists.txt;272;add_test;/home/runner/work/ggml/ggml/tests/CMakeLists.txt;0;")
add_test(test-rel-pos "/home/runner/work/ggml/ggml/_codeql_build_dir/bin/test-rel-pos")
set_tests_properties(test-rel-pos PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/ggml/ggml/tests/CMakeLists.txt;280;add_test;/home/runner/work/ggml/ggml/tests/CMakeLists.txt;0;")
add_test(test-customop "/home/runner/work/ggml/ggml/_codeql_build_dir/bin/test-customop")
set_tests_properties(test-customop PROPERTIES  ENVIRONMENT "LLVM_PROFILE_FILE=test-customop.profraw" _BACKTRACE_TRIPLES "/home/runner/work/ggml/ggml/tests/CMakeLists.txt;291;add_test;/home/runner/work/ggml/ggml/tests/CMakeLists.txt;0;")
add_test(test-conv1d "/home/runner/work/ggml/ggml/_codeql_build_dir/bin/test-conv1d")
set_tests_properties(test-conv1d PROPERTIES  ENVIRONMENT "LLVM_PROFILE_FILE=test-conv1d.profraw" _BACKTRACE_TRIPLES "/home/runner/work/ggml/ggml/tests/CMakeLists.txt;300;add_test;/home/runner/work/ggml/ggml/tests/CMakeLists.txt;0;")
add_test(test-conv1d-dw-c1 "/home/runner/work/ggml/ggml/_codeql_build_dir/bin/test-conv1d-dw-c1")
set_tests_properties(test-conv1d-dw-c1 PROPERTIES  ENVIRONMENT "LLVM_PROFILE_FILE=test-conv1d-dw-c1.profraw" _BACKTRACE_TRIPLES "/home/runner/work/ggml/ggml/tests/CMakeLists.txt;309;add_test;/home/runner/work/ggml/ggml/tests/CMakeLists.txt;0;")
add_test(test-conv1d-dw-c2 "/home/runner/work/ggml/ggml/_codeql_build_dir/bin/test-conv1d-dw-c2")
set_tests_properties(test-conv1d-dw-c2 PROPERTIES  ENVIRONMENT "LLVM_PROFILE_FILE=test-conv1d-dw-c2.profraw" _BACKTRACE_TRIPLES "/home/runner/work/ggml/ggml/tests/CMakeLists.txt;318;add_test;/home/runner/work/ggml/ggml/tests/CMakeLists.txt;0;")
add_test(test-conv2d "/home/runner/work/ggml/ggml/_codeql_build_dir/bin/test-conv2d")
set_tests_properties(test-conv2d PROPERTIES  ENVIRONMENT "LLVM_PROFILE_FILE=test-conv2d.profraw" _BACKTRACE_TRIPLES "/home/runner/work/ggml/ggml/tests/CMakeLists.txt;327;add_test;/home/runner/work/ggml/ggml/tests/CMakeLists.txt;0;")
add_test(test-conv2d-dw "/home/runner/work/ggml/ggml/_codeql_build_dir/bin/test-conv2d-dw")
set_tests_properties(test-conv2d-dw PROPERTIES  ENVIRONMENT "LLVM_PROFILE_FILE=test-conv2d-dw.profraw" _BACKTRACE_TRIPLES "/home/runner/work/ggml/ggml/tests/CMakeLists.txt;336;add_test;/home/runner/work/ggml/ggml/tests/CMakeLists.txt;0;")
add_test(test-cont "/home/runner/work/ggml/ggml/_codeql_build_dir/bin/test-cont")
set_tests_properties(test-cont PROPERTIES  ENVIRONMENT "LLVM_PROFILE_FILE=test-cont.profraw" _BACKTRACE_TRIPLES "/home/runner/work/ggml/ggml/tests/CMakeLists.txt;345;add_test;/home/runner/work/ggml/ggml/tests/CMakeLists.txt;0;")
add_test(test-interpolate "/home/runner/work/ggml/ggml/_codeql_build_dir/bin/test-interpolate")
set_tests_properties(test-interpolate PROPERTIES  ENVIRONMENT "LLVM_PROFILE_FILE=test-interpolate.profraw" _BACKTRACE_TRIPLES "/home/runner/work/ggml/ggml/tests/CMakeLists.txt;354;add_test;/home/runner/work/ggml/ggml/tests/CMakeLists.txt;0;")
